CREATE OR REPLACE FUNCTION AUTOGEN_ID_PELANGGAN
RETURN VARCHAR2
IS
    HASIL PELANGGAN.ID%TYPE;
BEGIN

    SELECT MAX(ID) + 1 INTO HASIL FROM PELANGGAN;

    RETURN HASIL;
END;
/
SHOW ERR;

CREATE OR REPLACE TRIGGER AUTOGEN_ID_BAHAN
BEFORE INSERT ON BAHAN
FOR EACH ROW
DECLARE
    ID varchar2(100);
BEGIN
    select to_char(max(to_number(ID))+1)
    into ID
    from BAHAN;

    :new.ID := ID;
END;
/